#-----------------------------------------------------------------------
#   application 인증 설정
#-----------------------------------------------------------------------

app:
  # 암호화 알고리즘
  encrypt:
    alg: SHA-256
    passwd: gdyYs/IZqY86VcWhT8emCYfqY1ahw2vtLG+/FzNqtrQ=
  jasypt:
    secretKey: xit5811807!@
    alg: PBEWithMD5AndDES
    type: base64
  token:
    typ: JWT
    alg: HS512
    grant: Bearer
    issuer: xit
    audience: ${app.name}
    # day
    tokenExpiry: 1
    # day
    refreshTokenExpiry: 7
    apiKey: lf2McyT3V5gDu2pNNm4VxmX3C2mezX3s
    #secretKey: 8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds
    secretKey: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
    # 토큰 재발급시 토큰(refresh) 전달 방식 : COOKIE | HEADER | DTO
    saveType: HEADER

  # mybatis config
# 사용자 ID 정보를 어디에 저장할 것인지 설정
# JWT 토큰을 사용하고 SessionCreationPolicy.STATELESS인 경우는 SecurityContext 사용불가
# --> session에 저장하는 방식은 가능
# security | session | header
# jwt secret key 설정
#jwt.secret: 8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds
# 토큰 재발급시 토큰(refresh) 전달 방식 : COOKIE | HEADER | DTO
#jwt.refresh.save.type: COOKIE
#jwt.secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LWlucGl4LWNvcmUtamF2YWZyYW1ld29yay1qYXZhLXRva2VuLWtleQ
